version: "3"

services:

  janeway-postgres:
    image: postgres:11
    volumes:
      - ./janeway/db/postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}"
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_DB=${DB_NAME}"
    depends_on:
      - janeway-pgadmin

  janeway-pgadmin:
    image: dpage/pgadmin4
    user: root
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    environment:
            - PGADMIN_DEFAULT_EMAIL=dev@janeway.systems
            - "PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}"
            - PG_ADMIN_LISTEN_ADDRESS=0.0.0.0
            - GUNICORN_THREADS=2
            - PGADMIN_SERVER_JSON_FILE=/var/lib/pgadmin/servers.json
            - PGADMIN_CONFIG_SERVER_MODE=False
            - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
     - "janeway-postgres"
     - janeway-debug-smtp
    command: "janeway-postgres:${DB_PORT}"

  janeway-web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./janeway/src:/vol/janeway/src
      - ./janeway/lib:/vol/janeway/lib
      - ./janeway/logs:/vol/janeway/logs
      - ./janeway/db/janeway.sqlite3:/db/janeway.sqlite3
    ports:
      - "${JANEWAY_PORT}:8000"
    environment:
      - DB_VENDOR
      - DB_HOST
      - DB_PORT
      - DB_PASSWORD
      - DB_USER
      - DB_NAME
      - PYTHONDONTWRITEBYTECODE=yes
      - JANEWAY_SETTINGS_MODULE=core.dev_settings
      - NOSE_INCLUDE_EXE=1
      - JANEWAY_EMAIL_BACKEND
      - JANEWAY_EMAIL_HOST
      - JANEWAY_EMAIL_PORT
      - JANEWAY_EMAIL_USE_TLS
      - JANEWAY_ENABLE_ORCID
      - JANEWAY_PRESS_NAME
      - JANEWAY_PRESS_DOMAIN
      - JANEWAY_PRESS_CONTACT
      - JANEWAY_JOURNAL_CODE
      - JANEWAY_JOURNAL_NAME
      - STATIC_DIR
      - MEDIA_DIR
      - JANEWAY_SUPERUSER_USERNAME
      - JANEWAY_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
    depends_on:
      - "start_dependencies"

  janeway-sqlite:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    volumes:
      - ./janeway/db/janeway.sqlite:/var/lib/janeway.sqlite
  janeway-debug-smtp:
    # Use same python as janeway-web to reduce the number of images
    image: python:3.8
    entrypoint: python -u -m smtpd -c DebuggingServer -n 0.0.0.0:1025