version: "1"

services:

  janeway-postgres:
    image: postgres:12
    networks:
      - janeway-net
    volumes:
      - ./dockervols/postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}"
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_DB=${DB_NAME}"
    depends_on:
      - janeway-pgadmin

  janeway-pgadmin:
    image: dpage/pgadmin4
    networks:
      - janeway-net
    user: root
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./dockervols/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@janeway.systems
      - "PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}"
      - PG_ADMIN_LISTEN_ADDRESS=0.0.0.0
      - GUNICORN_THREADS=2
      - PGADMIN_SERVER_JSON_FILE=/var/lib/pgadmin/servers.json
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False

  janeway-debug-smtp:
    # Use same python as janeway-web to reduce the number of images
    networks:
      - janeway-net
    image: python:3.8
    entrypoint: python -u -m smtpd -c DebuggingServer -n 0.0.0.0:1025

  start_janeway_dependencies:
    image: dadarek/wait-for-dependencies
    networks:
      - janeway-net
    depends_on:
     - "janeway-postgres"
     - janeway-debug-smtp
    command: "janeway-postgres:${DB_PORT}"

  start_nginx_dependencies:
    image: dadarek/wait-for-dependencies
    networks:
      - janeway-net
    depends_on:
     - "janeway-web"
    command: "janeway-web:${JANEWAY_PORT}"

  janeway-web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - janeway-net
    volumes:
      - ./dockervols/files:/vol/janeway/src/files
      - ./dockervols/plugins:/vol/janeway/src/plugins
      - ./dockervols/lib:/vol/janeway/lib
      - ./dockervols/janeway/collected-static:/var/www/janeway/collected-static
      - ./dockervols/janeway/media:/var/www/janeway/media
      - ./dockervols/janeway/logs:/var/www/janeway/logs
      - ./dockervols/janeway/state-data:/var/www/janeway/state-data
      - ./dockervols/run:/run
      - ./dockervols/cron:/var/spool/cron/crontabs
    environment:
      - DB_VENDOR
      - DB_HOST
      - DB_PORT
      - DB_PASSWORD
      - DB_USER
      - DB_NAME
      - JANEWAY_PORT
      - PYTHONDONTWRITEBYTECODE=yes
      - NOSE_INCLUDE_EXE=1
      - JANEWAY_EMAIL_BACKEND
      - JANEWAY_EMAIL_HOST
      - JANEWAY_EMAIL_PORT
      - JANEWAY_EMAIL_USE_TLS
      - JANEWAY_ENABLE_ORCID
      - JANEWAY_PRESS_NAME
      - JANEWAY_PRESS_DOMAIN
      - JANEWAY_PRESS_CONTACT
      - JANEWAY_JOURNAL_CODE
      - JANEWAY_JOURNAL_NAME
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - JANEWAY_VERSION
      - INSTALL_CRON
      - INSTALL_TYPESETTING_PLUGIN=True
      - INSTALL_PANDOC_PLUGIN=True
      - INSTALL_CUSTOMSTYLING_PLUGIN=False
      - INSTALL_PORTICO_PLUGIN=False
      - INSTALL_IMPORTS_PLUGIN=False
      - INSTALL_DOAJ_TRANSPORTER_PLUGIN=False
      - INSTALL_BACK_CONTENT_PLUGIN=False
      - INSTALL_REPORTING_PLUGIN=False
    depends_on:
      - "start_janeway_dependencies"

  janeway-nginx:
    ports:
      - "${JANEWAY_PORT}:${JANEWAY_PORT}"
    image: nginx:latest
    networks:
      - janeway-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dockervols/janeway/collected-static:/var/www/janeway/collected-static
      - ./dockervols/janeway/media:/var/www/janeway/media
    depends_on:
      - start_nginx_dependencies

networks:
  janeway-net: